### ISSUE TITLE
net can't forward?

### ISSUE THREAD

**Issue by cuixing158** [matlab-deep-learning/mask-rcnn#1]
Even if batchsize=1, the out of memory error still occurs. My basic configuration is as follows:
gpu: GTX1070-8g
matlab2020b
Changing to resnet50 backbone also does not work !
```matlab
% Evaluate the model gradients and loss using dlfeval
 [gradients, loss, state] = dlfeval(@networkGradients, X, gtBox, gtClass, gtMask, dlnet, params);% out of memory!
```
Error using nnet.internal.cnn.dlnetwork/forward (line 254)
Layer 'res5b': Invalid input data. Out of memory on device. To view more detail about available memory on the GPU, use 'gpuDevice()'. If the problem persists, reset the GPU by calling 'gpuDevice(1)'.
Error in nnet.internal.cnn.dlnetwork/CodegenOptimizationStrategy/propagateWithFallback (line 103)
                [varargout{1:nargout}] = fcn(net, X, layerIndices, layerOutputIndices);
Error in nnet.internal.cnn.dlnetwork/CodegenOptimizationStrategy/forward (line 52)
            [varargout{1:nargout}] = propagateWithFallback(strategy, functionSlot, @forward, net, X, layerIndices, layerOutputIndices);
Error in dlnetwork/forward (line 347)
                [varargout{1:nargout}] = net.EvaluationStrategy.forward(net.PrivateNetwork, x, layerIndices, layerOutputIndices);
Error in networkGradients (line 22)
[YRPNRegDeltas, proposal, YRCNNClass, YRCNNReg, YRPNClass, YMask, state] = forward(...
Error in deep.internal.dlfeval (line 18)
[varargout{1:nout}] = fun(x{:});
Error in dlfeval (line 41)
    [varargout{1:nout}] = deep.internal.dlfeval(fun,varargin{:});

**Comment by anchitdharmw** [comment]
Hi @cuixing158, The mask-rcnn in the example is trained on 800x800x3 images. One recommendation here could be trying out a smaller image size.
